name: client-components
on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - b-*
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        component: [octelium]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Set ENV variables
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: for v in `cat .github/workflows/env` ; do echo "::set-env name=${v%%=*}::${v##*=}" ; done
      - name: Set is latest
        run: |
          IS_LATEST=$(git tag | grep -E "^v[0-9]+\.[0-9]+\.[0-9]+$" | sort -r --version-sort | head -n1)
          echo $IS_LATEST
          if [ "$IS_LATEST" = ${{ env.GITHUB_REF_SLUG }} ]; then
            echo "V_IS_LATEST=true" >> $GITHUB_ENV
          else
            echo "V_IS_LATEST=false" >> $GITHUB_ENV
          fi

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{env.V_CONTAINER_REGISTRY}}/${{env.V_ORG}}/${{matrix.component}}
          flavor: |
            latest=${{env.V_IS_LATEST}}
            prefix=
            suffix=
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Registry
        uses: docker/login-action@v2
        with:
          registry: ${{env.V_CONTAINER_REGISTRY}}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.OCTELIUM_REGISTRY }}

      - name: Publish to Registry
        uses: docker/build-push-action@v3
        env:
          IMAGE_TAG: ${{ env.GITHUB_REF_SLUG }}
        with:
          context: .
          file: client/${{matrix.component}}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
